### ISSUE TITLE
Could not access the frontend application

### ISSUE THREAD

**Issue by geokal** [berdav/unibo-test-mec#3]
Hi , am trying to start both application and mec  on docker desktop mac  but i could not reach the frontend for both? Should i pass the -p parameter like -p 8080:80  or the EXPOSE parameter on Dockerfile? Thanks in advance.

**Comment by berdav** [comment]
Hi,

unfortunately I don't have MacOS at the moment.
On GNU/Linux you can access to the Docker machine using the following methods:

- Using port forwarding: as you were saying, you can expose the port to the external world using a command similar to this one:

```
# docker run --rm -ti \
        -e MEC_BASE="http://172.17.0.3:80" \
        -e APP_INSTANCE_ID="997fc80a-cfc1-498a-b77f-608f09506e86" \
        -p 8080:80 \
        unibo-test-mec-application
```
  Then you can connect to the application pointing your browser to
  localhost:8080.

- If you setup the frontend using `./run-local.sh` you can access the frontend using its IP address.  You can find the address using `docker inspect $containerid | grep IPAddress`.  The containerid is the one returned by `docker ps`.

  For instance:  
![image](https://user-images.githubusercontent.com/1332095/102752447-e6ef4680-4369-11eb-8b33-32a7a728b1d2.png)
![image](https://user-images.githubusercontent.com/1332095/102752466-ee165480-4369-11eb-8a43-e93cb9dedaf8.png)


  And now you can access to the frontend using 172.17.0.2:80

Let me know if you still have this issue.

**Comment by berdav** [comment]
Furthermore, probably its better to expose the port to the localhost only using `-p 127.0.0.1:8080:80`.

**Comment by geokal** [comment]
Thanks for your answer! So yesterday I managed to make it work by using the folowing on run-local.sh
```
#!/bin/sh

set -eu

cd docker-img-application
./build.sh
cd -

docker run --rm -ti \
        -e MEC_BASE="http://172.17.0.3:80" \
        -e APP_INSTANCE_ID="997fc80a-cfc1-498a-b77f-608f09506e86" \
	-p 56733:80 \
	unibo-test-mec-application
```

and the on run-mec.sh similar to the above:
```
#!/bin/sh

set -eu

cd docker-img-mec
./build.sh
cd -

docker run --rm -ti \
        -e APP_INSTANCE_ID="997fc80a-cfc1-498a-b77f-608f09506e86" \
	-p 56734:80 \
	unibo-test-mec-mec
```

so it's similar to what you are proposing . Perfect thanks a lot. Now i have to see how can i test some of the etsi mec api's thanks for your help :)

**Comment by berdav** [comment]
Thank to you!

I'm closing the issue for now, feel free to open another one if you find something which is not clear or don't work.

Good luck with the APIs. :)
